### ISSUE TITLE
处理缺失值问题

### ISSUE THREAD

**Issue by JJMLeo** [chenchiwei/tradaboost#12]
### 1、请问**处理缺失值**为什么用这个语句呢？
`train_df.fillna(value=-999999)`
### 2、不知道是不是我设置的内存不够，运行程序的时候还是报错
```
Traceback (most recent call last):
  File "Tradaboost_GitHub.py", line 98, in <module>
    pred = tr.tradaboost(X_train, trans_T, y_train, label_T, X_test, 10)
  File "TrAdaboost.py", line 44, in tradaboost
    result_label[:, i] = train_classify(trans_data, trans_label,test_data, P)
  File "TrAdaboost.py", line 89, in train_classify
    clf.fit(trans_data, trans_label, sample_weight=P[:, 0])
  File "sklearn\tree\tree.py", line 790, in fit
    X_idx_sorted=X_idx_sorted)
  File "sklearn\tree\tree.py", line 117, in fit
    y = check_array(y, ensure_2d=False, dtype=None)
  File "sklearn\utils\validation.py", line 422, in check_array
    _assert_all_finite(array)
  File "sklearn\utils\validation.py", line 43, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
非常感谢给出源代码！

**Comment by JJMLeo** [comment]
好像这个issues有点弱鸡OmO可是搞了很长时间没有解决，不知道怎么办了。
内存设置为512M/2048M

**Comment by JJMLeo** [comment]
我是用的这个数据https://www.kesci.com/home/competition/5ca1b155bcf47e002c38ba66/content/2

**Comment by JJMLeo** [comment]
The problem is solved. 
I used the following code to process missing values.
`df.fillna(value=-999999,inplace=True)`
